Feature/ujian project uts
praks27/project_uts_Laravel pull request #1
Opened 2022-10-29 01:38 UTC by praks27

2022-10-29 02:53 UTC, Arudisan commented on resources/views/pages/category/list-category.blade.php
> +    <h3>jurusan {{ $categories->name }} </h3>
Mohon diubah menjadi nama kategori saja biar jelas

2022-10-29 02:53 UTC, Arudisan commented on resources/views/pages/category/list-category.blade.php
> +    <h4>Jumlah Siswa :{{ $categories->products->count() }}</h4>
Ini jumlah produk ?

2022-10-29 02:53 UTC, Arudisan commented on resources/views/pages/category/list-category.blade.php
> +        <th scope="col">Student Name</th>
apakah nama produk ? jika iya diubah saja

2022-10-29 02:56 UTC, gafriputra requested changes
1. Jangan lupa format document biar codenya rapi
2. Overall is good 👍

2022-10-29 02:56 UTC, gafriputra commented on app/Http/Controllers/CategoryController.php
> +        //
hapus aja klk gaada commentnya

2022-10-29 02:56 UTC, gafriputra commented on app/Http/Controllers/CategoryController.php
> +        //
same as above

2022-10-29 02:56 UTC, gafriputra commented on app/Http/Controllers/ProductController.php
> +        // dd($request->file('image')->store('product'));
debugnya dihapus aja klk udah gadibutuhin

2022-10-29 02:56 UTC, gafriputra commented on app/Http/Controllers/ProductController.php
> +        $data['image'] = $request->file('image')->store('images/product','public');
dihapus ya, udah ada diatasnya, jadi double code

2022-10-29 02:56 UTC, gafriputra commented on app/Http/Requests/StoreProductRequest.php
> +            "status" => "required",
ini harusnya enum kayak yang dimigrationnya

2022-10-29 02:56 UTC, gafriputra commented on app/Http/Requests/UpdateProductRequest.php
> +            "status" => "required",
pakai enum ya

2022-10-29 02:56 UTC, gafriputra commented on database/seeders/CategorySeeder.php
> +<?php
coba diimplementasikan seedernya

2022-10-29 02:56 UTC, gafriputra commented on database/seeders/ProductSeeder.php
> +<?php
same as above

2022-10-29 02:56 UTC, gafriputra commented on resources/views/pages/category/list-category.blade.php
> +    <h3>jurusan {{ $categories->name }} </h3>
namanya masih jurusan dan jumlah siswanya ke title yang sesuai

2022-10-29 02:56 UTC, gafriputra commented on resources/views/pages/category/list.blade.php
> +@extends('layouts.dashboard')
coba pakai pagination juga

2022-10-29 02:57 UTC, rabbitz215 requested changes
1.Comment tidak bersangkutan bisa dihapus

2022-10-29 02:57 UTC, rabbitz215 commented on app/Http/Controllers/ProductController.php
> +        // if ($search) {
Dihapus aja kalo tidak digunakan

2022-10-29 02:57 UTC, rabbitz215 commented on app/Http/Controllers/ProductController.php
> +        // $data = student::with(['major'])->get();
Sama seperti diatas

2022-10-29 02:59 UTC, rahmadxhidayat1 reviewed
kesimpulan hapus code yang tidak dipakai

2022-10-29 02:59 UTC, rahmadxhidayat1 commented on app/Http/Controllers/ProductController.php
> +        // select * from students where name like '%$search%'
dihilangkan kode yang tidak dipakai

2022-11-03 04:28 UTC, praks27 commented on app/Http/Controllers/CategoryController.php
> +        //
sudah mas silahkan di cek lagi

2022-11-03 04:28 UTC, praks27 commented on app/Http/Controllers/ProductController.php
> +        $data['image'] = $request->file('image')->store('images/product','public');
sudah mas silahkan di cek lagi

2022-11-03 04:29 UTC, praks27 commented on app/Http/Requests/StoreProductRequest.php
> +            "status" => "required",
sudah mas silahkan di cek lagi

2022-11-03 04:29 UTC, praks27 commented on database/seeders/CategorySeeder.php
> +<?php
sudah di implementasikan mas seedernya silahkan di cek

2022-11-03 04:30 UTC, praks27 commented on resources/views/pages/category/list-category.blade.php
> +    <h3>jurusan {{ $categories->name }} </h3>
sudah di ganti mas

2022-11-03 05:22 UTC, praks27 commented on resources/views/pages/category/list.blade.php
> +@extends('layouts.dashboard')
sudah  ditambahkan mas

2022-11-23 11:23 UTC, merged